<?php

declare(strict_types=1);

namespace Iniznet\Mahout\Devtools\Stubs;

/**
 * Renders WordPress declarations as a PHPStan stub file.
 *
 * The symbol sets are collected by reflection after core is booted, so every
 * signature, default and docblock comes from the installed core rather than
 * from a hand-maintained list. Functions and constants are grouped and sorted;
 * classes are emitted in the dependency order the caller supplies, because the
 * file is loaded by PHP as a bootstrap and a parent must precede its child.
 */
final readonly class StubGenerator
{
    private const string HEADER = 'This file is generated by mahout-devtools from the installed WordPress core. Do not edit by hand; run composer stubs:generate.';

    private const string INDENT = '    ';

    /**
     * @param list<callable-string> $functions
     * @param list<class-string>    $classes   dependency-ordered: parents before children
     * @param array<string, mixed>  $constants
     */
    public function __construct(
        private array $functions,
        private array $classes,
        private array $constants,
    ) {
    }

    public function render(): string
    {
        $output = '<?php'.PHP_EOL.PHP_EOL;
        $output .= '/**'.PHP_EOL
            .' * WordPress core declarations.'.PHP_EOL
            .' *'.PHP_EOL
            .' * '.self::HEADER.PHP_EOL
            .' */'.PHP_EOL;
        $output .= 'declare(strict_types=1);'.PHP_EOL;

        $constants = '';
        foreach ($this->constants as $name => $value) {
            if (!$this->isRenderableConstant($value)) {
                continue;
            }
            $constants .= sprintf('define(%s, %s);', var_export($name, true), var_export($value, true)).PHP_EOL;
        }
        if ('' !== $constants) {
            $output .= PHP_EOL.'namespace {'.PHP_EOL.$constants.'}'.PHP_EOL;
        }

        $functions = $this->functions;
        sort($functions, SORT_STRING);

        $functionGroups = [];
        foreach ($functions as $function) {
            $reflection = new \ReflectionFunction($function);
            $functionGroups[$reflection->getNamespaceName()][] = $this->renderFunction($reflection);
        }

        $namespaces = array_keys($functionGroups);
        sort($namespaces, SORT_STRING);
        foreach ($namespaces as $namespace) {
            $output .= PHP_EOL;
            $output .= '' === $namespace ? 'namespace {' : 'namespace '.$namespace.' {';
            $output .= PHP_EOL;
            $output .= implode(PHP_EOL, $functionGroups[$namespace]);
            $output .= '}'.PHP_EOL;
        }

        foreach ($this->classes as $class) {
            $reflection = new \ReflectionClass($class);
            $namespace = $reflection->getNamespaceName();

            $output .= PHP_EOL;
            $output .= '' === $namespace ? 'namespace {' : 'namespace '.$namespace.' {';
            $output .= PHP_EOL;
            $output .= $this->renderClass($reflection);
            $output .= '}'.PHP_EOL;
        }

        return $output;
    }

    private function isRenderableConstant(mixed $value): bool
    {
        return null === $value || \is_scalar($value) || \is_array($value);
    }

    private function renderFunction(\ReflectionFunction $function): string
    {
        $signature = sprintf(
            'function %s%s(%s)%s',
            $function->returnsReference() ? '&' : '',
            $function->getShortName(),
            $this->renderParameters($function->getParameters()),
            $this->renderReturnType($function->getReturnType()),
        );

        return $this->renderDocblock($function->getDocComment()).$signature.' {'.PHP_EOL.'}'.PHP_EOL;
    }

    /**
     * @param \ReflectionClass<object> $class
     */
    private function renderClass(\ReflectionClass $class): string
    {
        $kind = 'class';
        if ($class->isInterface()) {
            $kind = 'interface';
        } elseif ($class->isTrait()) {
            $kind = 'trait';
        } elseif ($class->isEnum()) {
            $kind = 'enum';
        }

        $prefix = '';
        if ('class' === $kind && $class->isAbstract()) {
            $prefix .= 'abstract ';
        }
        if ('class' === $kind && $class->isFinal()) {
            $prefix .= 'final ';
        }

        $extends = '';
        $parent = $class->getParentClass();
        if (false !== $parent) {
            $extends = ' extends \\'.$parent->getName();
        }

        $interfaces = $class->getInterfaceNames();
        $implements = [] === $interfaces ? '' : ' implements '.implode(', ', array_map(
            static fn (string $name): string => '\\'.$name,
            $interfaces,
        ));

        return $this->renderDocblock($class->getDocComment())
            .$prefix.$kind.' '.$class->getShortName().$extends.$implements.' {'.PHP_EOL
            .$this->renderClassMembers($class)
            .'}'.PHP_EOL;
    }

    /**
     * @param \ReflectionClass<object> $class
     */
    private function renderClassMembers(\ReflectionClass $class): string
    {
        $members = '';

        foreach ($class->getReflectionConstants() as $constant) {
            if ($constant->getDeclaringClass()->getName() !== $class->getName() || $constant->isPrivate()) {
                continue;
            }
            $members .= $this->renderClassConstant($constant);
        }

        foreach ($class->getProperties() as $property) {
            if ($property->getDeclaringClass()->getName() !== $class->getName() || $property->isPrivate()) {
                continue;
            }
            $members .= $this->renderProperty($property);
        }

        foreach ($class->getMethods() as $method) {
            if ($method->getDeclaringClass()->getName() !== $class->getName() || $method->isPrivate()) {
                continue;
            }
            $members .= $this->renderMethod($method);
        }

        return $members;
    }

    private function renderReturnType(?\ReflectionType $type): string
    {
        if (null === $type) {
            return '';
        }

        return ': '.$this->renderType($type);
    }

    private function renderType(\ReflectionType $type): string
    {
        if ($type instanceof \ReflectionUnionType) {
            $parts = [];
            foreach ($type->getTypes() as $member) {
                $parts[] = $this->renderType($member);
            }

            return implode('|', $parts);
        }

        if ($type instanceof \ReflectionIntersectionType) {
            $parts = [];
            foreach ($type->getTypes() as $member) {
                $parts[] = $this->renderType($member);
            }

            return implode('&', $parts);
        }

        if (!$type instanceof \ReflectionNamedType) {
            return 'mixed';
        }

        $name = $type->getName();
        $nullable = $type->allowsNull() && !\in_array($name, ['mixed', 'null'], true);
        $special = \in_array($name, ['self', 'static', 'parent'], true);

        if ($type->isBuiltin() || $special) {
            $rendered = $name;
        } else {
            $rendered = '\\'.ltrim($name, '\\');
        }

        return $nullable ? '?'.$rendered : $rendered;
    }

    /**
     * @param list<\ReflectionParameter> $parameters
     */
    private function renderParameters(array $parameters): string
    {
        $rendered = [];
        foreach ($parameters as $parameter) {
            $part = '';
            $type = $parameter->getType();
            if (null !== $type) {
                $part .= $this->renderType($type).' ';
            }
            if ($parameter->isPassedByReference()) {
                $part .= '&';
            }
            if ($parameter->isVariadic()) {
                $part .= '...';
            }
            $part .= '$'.$parameter->getName();

            if (!$parameter->isVariadic() && $parameter->isOptional() && $parameter->isDefaultValueAvailable()) {
                $part .= ' = '.var_export($parameter->getDefaultValue(), true);
            }

            $rendered[] = $part;
        }

        return implode(', ', $rendered);
    }

    private function renderDocblock(string|false $docblock): string
    {
        if (false === $docblock || '' === $docblock) {
            return '';
        }

        $lines = preg_split('/\R/', $docblock);
        if (false === $lines) {
            return '';
        }

        return implode(PHP_EOL, array_map(rtrim(...), $lines)).PHP_EOL;
    }

    private function renderProperty(\ReflectionProperty $property): string
    {
        $visibility = $property->isProtected() ? 'protected' : 'public';
        $static = $property->isStatic() ? ' static' : '';
        $type = $property->hasType() ? ' '.$this->renderType($property->getType()) : '';
        $default = '';
        if ($property->hasDefaultValue() && !$property->isStatic()) {
            $default = ' = '.var_export($property->getDefaultValue(), true);
        }

        return $this->renderDocblock($property->getDocComment())
            .self::INDENT.$visibility.$static.$type.' $'.$property->getName().$default.';'.PHP_EOL;
    }

    private function renderClassConstant(\ReflectionClassConstant $constant): string
    {
        if ($constant->isEnumCase()) {
            return self::INDENT.'case '.$constant->getName().';'.PHP_EOL;
        }

        $visibility = $constant->isProtected() ? 'protected' : 'public';
        $value = $constant->getValue();

        if (!$this->isRenderableConstant($value)) {
            return '';
        }

        return $this->renderDocblock($constant->getDocComment())
            .self::INDENT.$visibility.' const '.$constant->getName().' = '.var_export($value, true).';'.PHP_EOL;
    }

    private function renderMethod(\ReflectionMethod $method): string
    {
        $declaringClass = $method->getDeclaringClass();
        $modifiers = $method->isProtected() ? 'protected' : 'public';
        if ($method->isAbstract() && !$declaringClass->isInterface()) {
            $modifiers = 'abstract '.$modifiers;
        }
        if ($method->isStatic()) {
            $modifiers .= ' static';
        }

        $signature = sprintf(
            '%s%s function %s%s(%s)%s',
            self::INDENT,
            $modifiers,
            $method->returnsReference() ? '&' : '',
            $method->getName(),
            $this->renderParameters($method->getParameters()),
            $this->renderReturnType($method->getReturnType()),
        );

        $end = ($method->isAbstract() || $declaringClass->isInterface())
            ? ';'
            : ' {'.PHP_EOL.self::INDENT.'}';

        return $this->renderDocblock($method->getDocComment()).$signature.$end.PHP_EOL;
    }
}
