<?php

declare(strict_types=1);

namespace Iniznet\Mahout\Devtools\Generator\Hooks;

use Iniznet\Mahout\Devtools\Generator\GeneratedReference;

/**
 * One kind of hook, rendered as its own reference document.
 *
 * The scan lives in HooksReference; this is the rendering half, and the split is the
 * whole point of it: actions and filters answer different questions for the person
 * reading the file, so they get different files. Definitions whose kind is the other one
 * are not silently dropped from the family's documentation — they are in the sibling file,
 * and every document says so.
 *
 * A kind with no hooks still gets a document, because a gate that only ever checks a file
 * that exists when there is something to say is a gate that quietly stops running.
 *
 * @internal
 */
final readonly class HookDocument implements GeneratedReference
{
    /**
     * @param list<HookDefinition> $definitions
     */
    public function __construct(
        private HookType $type,
        private array $definitions,
    ) {
    }

    #[\Override]
    public function kind(): string
    {
        return $this->type->kind();
    }

    #[\Override]
    public function generate(): string
    {
        /** @var array<string, list<HookDefinition>> $byClass */
        $byClass = [];

        foreach ($this->definitions as $definition) {
            if ($definition->type !== $this->type) {
                continue;
            }

            $byClass[$definition->class][] = $definition;
        }

        ksort($byClass, SORT_STRING);

        $output = '# '.$this->type->heading().PHP_EOL.PHP_EOL
            .'Generated by `mahout-devtools`. Do not edit by hand; run `composer hooks:generate`.'.PHP_EOL
            .PHP_EOL
            .'Every hook name is a `public const` on a `Hooks` class; its `@action` or `@filter`'
            .' docblock tag decides which of the two documents the entry lands in.'.PHP_EOL
            .'The other kind lives in `'.$this->type->siblingFileName().'`.'.PHP_EOL
            .PHP_EOL;

        if ([] === $byClass) {
            return $output.'This package declares no '.$this->type->value.'s.'.PHP_EOL;
        }

        $output .= '| Constant | Hook | Arguments | Since | Description |'.PHP_EOL
            .'|---|---|---|---|---|'.PHP_EOL;

        foreach ($byClass as $class => $definitions) {
            foreach ($definitions as $definition) {
                $output .= '| `'.$definition->constant.'` | `'.$definition->hook.'`'
                    .' | '.$this->renderArguments($definition)
                    .' | '.$this->renderCell($definition->since)
                    .' | '.$this->renderCell($definition->description).' |'.PHP_EOL;
            }
        }

        return $output;
    }

    private function renderArguments(HookDefinition $definition): string
    {
        if ([] === $definition->arguments) {
            return '—';
        }

        return implode(', ', array_map(
            static fn (string $argument): string => '`'.$argument.'`',
            $definition->arguments,
        ));
    }

    private function renderCell(string $value): string
    {
        $value = str_replace(['|', PHP_EOL], ['\\|', ' '], trim($value));

        return '' === $value ? '—' : $value;
    }
}
